### ISSUE TITLE
rightAnsIds

### ISSUE THREAD

**Issue by Kirill02089** [Flint01686/web-lessons#2]
```rightAnsIds``` - right anus ids? Если я не прав, то поправь меня

https://github.com/Flint01686/web-lessons/blob/296e05cab5d0292a1d4524f13f7e95ec31bb53cf/src/index.js#L84

Пиши. Читаемые. Переменные.
Мы не будем писать ниндзя код, мы пишем простой, понятный, юзер френдли код, с комментариями.

P.S. вот что такое ниндзя код
https://learn.javascript.ru/ninja-code

**Comment by Flint01686** [comment]
undstdNonijaPeremenaia = true

ладно, больше не буду)))..

noNinjaCodingStyle = true

**Comment by Kirill02089** [comment]
Done
